/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wall2ban.fail2ban.actionforms;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import wall2ban.DeleteForm;
import wall2ban.fail2ban.Action;
import wall2ban.fail2ban.ActionStore;

/**
 *
 * @author ADMIN
 */
public class ManageActionsForm extends javax.swing.JFrame {
    /**
     * DAO for actions management.
     */
    private ActionStore actionStore;
    
    /**
     * Creates new form ManageActionsForm
     */
    public ManageActionsForm(ActionStore actionStore) {
        initComponents();
        this.actionStore = actionStore;
        
        bindActionsList();
    }
    /**
     * Creates new action names list and sets it to list model.
     */
    private void bindActionsList(){
        List<String> actionNames = new ArrayList<String>();
        for(Action action : actionStore.readAll())
            actionNames.add(action.getName());
        Comparator c = new Comparator<String>(){
            @Override
            public int compare(String a, String b){return a.compareTo(b);}
        };
        actionNames.sort(c);
        DefaultListModel<String> model = new DefaultListModel<String>();
        model.addAll(actionNames);
        this.actionsJList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        actionsJList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        editButton = new javax.swing.JButton();
        createButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        definitionTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Definition");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        actionsJList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        actionsJList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                actionsJListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(actionsJList);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Actions");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        editButton.setText("Edit");
        editButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButtonActionPerformed(evt);
            }
        });

        createButton.setText("Create Action");
        createButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createButtonActionPerformed(evt);
            }
        });

        deleteButton.setText("Delete Action");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        definitionTextArea.setColumns(20);
        definitionTextArea.setRows(5);
        jScrollPane3.setViewportView(definitionTextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(createButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteButton)))
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(editButton)
                            .addComponent(createButton)
                            .addComponent(deleteButton))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        if(this.actionsJList.getSelectedIndex()>=0){    // checks if user clicked a valid item
            String actionName = this.actionsJList.getSelectedValue();   // gets selected action name
            Action action = actionStore.readByKey(actionName);  // gets action from list
            ConfigureActionDialog form = new ConfigureActionDialog(this,true,action); // creates new config form to edit action
            form.setVisible(true);
            if(form.getFormResult()){   // checks if operation succeeded
                Action newAction = form.getAction(); // gets updated action
                try {
                    actionStore.update(newAction);  // updates action
                    bindActionsList();      // updates actions list in view
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this, "Failed to update action.\nError: "+err.getMessage());
                }
                
            }
        }
    }//GEN-LAST:event_editButtonActionPerformed

    private void createButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createButtonActionPerformed
        if(this.actionsJList.getSelectedIndex()>=0){    // checks if user clicked a valid item
            ConfigureActionDialog form = new ConfigureActionDialog(this,true,null); // creates new config form to edit action
            form.setVisible(true);
            if(form.getFormResult()){   // checks if operation succeeded
                Action newAction = form.getAction(); // gets new action
                try {
                    actionStore.create(newAction);  // creates action
                    bindActionsList();      // updates actions list in view
                } catch (Exception err) {
                    JOptionPane.showMessageDialog(this, "Failed to create action.\nError: "+err.getMessage());
                }
                
            }
        }
    }//GEN-LAST:event_createButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        if(this.actionsJList.getSelectedIndex()>=0){    // checks if user clicked a valid item
            String actionName = this.actionsJList.getSelectedValue();   // gets selected action name
            Action action = actionStore.readByKey(actionName);  // gets action from list
            
            DeleteForm delForm = new DeleteForm(this,true);
            delForm.setMessage("Delete action "+action.getName());
            delForm.setVisible(true);
            if(delForm.getFormResult()){    // checks if operation succeeded
                try {
                    actionStore.delete(action); // deletes action
                    bindActionsList();      // updates actions list in view
                } catch (Exception err) {
                   JOptionPane.showMessageDialog(this, "Failed to delete action.\nError: "+err.getMessage());
                }
            }
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void actionsJListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_actionsJListMouseClicked
        int index = this.actionsJList.getSelectedIndex();
        if(index>=0){   // checks if user selected a valid item
            String actionName = this.actionsJList.getSelectedValue();
            Action action = actionStore.readByKey(actionName);    // gets action in list
            this.definitionTextArea.setText(action.toConfigString()); // sets config string for text area
            
        }
    }//GEN-LAST:event_actionsJListMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageActionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageActionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageActionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageActionsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ActionStore astore = new ActionStore();
                new ManageActionsForm(astore).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> actionsJList;
    private javax.swing.JButton createButton;
    private javax.swing.JTextArea definitionTextArea;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
